// ═══════════════════════════════════════════════════
//  data.js  — 모든 콘텐츠 데이터 (여기서 한 번에 수정)
// ═══════════════════════════════════════════════════

export const D = {
  /* ── 브랜드 */
  brand: {
    name: "DesignLab",
    tagline: "Crafting Brand Experience", // Arbutus 폰트
    subTagline: "비즈니스를 완성하는 여정", // Ycomputer 폰트
    copyright: "@2026 DESIGNLAB",
    author: "by KWAK SUN HEE",
    logoImg: "/images/dl_logo.png",
  },

  /* ── 프로필 */
  profile: {
    name: "곽선희 / Murgerbon",
    role: "Visual Junior Director · Packaging Designer",
    memojiImg: "/images/mypage_memoticon.png",
    chatMemojiImg: "/images/chatbot_online.png",
    chatGreetImg: "/images/chatbot_memoticon_01.png",
    chatBotBubbleImg: "/images/chatbot_memoticon_02.png",
    chatYouImg: "/images/chatbot_you.png",
    chatImg: "/images/chat.png",
    stats: [
      { value: "10+", label: "France Study" },
      { value: "2.11+", label: "Practice" },
      { value: "3", label: "Language" },
    ],
    languages: "KR / FR / EN",
    expertise: ["BX Strategy", "Package Production", "Art Direction"],
    philosophy: {
      title: "The Art of Logic :",
      subtitle: "논리로 빚어낸 브랜드의 격",
    },
  },

  /* ── 대시보드 */
  dashboard: {
    title: "The Art of Logic",
    subtitle: ": BX Synergy Report",
    desc: "10년의 글로벌 미학과 비즈니스 로직을 연결하여\n기업의 실질적 가치를 설계합니다.",
    filterTabs: ["BX", "Visual Dir.", "Production", "Digital/Ai"],
    skills: [
      {
        name: "Visual Communication",
        pct: 90,
        sub: "Brand Identity Design : Logo, Typography, Brand Guideline",
        detail: "타겟 분석 기반의 브랜드 정체성 확립 및 시각화",
        cat: "BX",
      },
      {
        name: "Photography & Videography",
        pct: 100,
        sub: "Commercial Photo, Film Directing, Lighting",
        detail: "비주얼 톤앤매너 (사진 & 영상) 디렉팅",
        cat: "Visual Dir.",
      },
      {
        name: "Packaging Production Mgmt",
        pct: 100,
        sub: "CMYK Color Control, Post-press, Inspection",
        detail: "정교한 도수 관리 및 현장 인쇄 감리를 통한 구현력 최적화",
        cat: "Production",
      },
      {
        name: "AI & Digital Tools",
        pct: 78,
        sub: "Figma, Gemini, Midjourney, Claude Vibe Coding",
        detail: "AI 바이브 코딩 레버리지 및 디지털 워크플로우 최적화",
        cat: "Digital/Ai",
      },
    ],
    chartBars: [
      { label: "BX", orange: 65, teal: 80 },
      { label: "Visual", orange: 90, teal: 100 },
      { label: "Pack.", orange: 45, teal: 60 },
      { label: "Prod.", orange: 80, teal: 100 },
      { label: "Digital", orange: 50, teal: 70 },
      { label: "Ai", orange: 70, teal: 78 },
    ],
  },

  /* ── 포트폴리오 (8개) */
  projects: [
    {
      id: 0,
      cat: "PACKAGING",
      genre: "Food",
      title: "Renewal",
      thumbnail: "/images/thumbnail_jerky.png",
      img: "/images/photo_jerky.png",
      bg: "#C8C4B8",
      isVideo: false,
      year: "2025",
      fullTitle: "머거본 육포 라인업 패밀리룩 리뉴얼",
      desc: ["기존 육포는 라인업이라는 개념 자체가 없었고, 육포 제품들이 개별 SKU로 각각 존재하던 상태였습니다. 그 결과 매대에서 '머거본 육포'라는 하나의 카테고리로 인지되지 않는 문제가 있었습니다.",
             "머거본의 '본'에서 출발해 한자 '本(근본)'으로 연결했습니다. 육포의 본질·정통이라는 제품 속성과 모브랜드 자산이 동시에 걸리는 지점을 찾는 데 집중했습니다.",
             "여러 방향성 시안을 검토한 결과, '本' 심볼을 중심으로 한 안을 최종 확장안으로 선정했습니다. 브랜드명 '머거본'에서 자연스럽게 연결되는 상징이라 별도의 학습 곡선 없이 브랜드-제품 연결이 즉각적으로 인지되고, 단일 한자 그래픽이라 사이즈·인쇄 조건에 관계없이 형태 손실 없이 확장 가능하다는 점에서 장기 라인업 자산으로서의 지속가능성이 가장 높다고 판단했습니다.",
             "'本' 심볼 위치·비중 고정, 맛별 컬러 코드 체계, 타이포 위계 규격화를 통해 신규 SKU 추가 시 디자이너가 바뀌어도 동일한 룩이 유지되는 시스템을 구축했습니다.",
             "이 시스템을 기반으로, 패밀리룩 구축 이후, 외부 IP 콜라보 시에는 기존 자산을 유지하는 자산 축적형과 협업 IP를 전면화하는 단기 주목형으로 구조를 나눠 제안하고, 브랜드 위계 정의를 선행 논의로 올리는 방식으로 운영 중입니다.",],
      tags: ["Package Design", "Renewal", "Visual Strategy", "Family-look", "Contribution · 50%"],
    },
    {
      id: 1,
      cat: "PACKAGING",
      genre: "Food",
      title: "Brand Identity",
      thumbnail: "/images/thumbnail_bellygom.png",
      img: "/images/belly_gom.png",
      bg: "#B8C4C0",
      isVideo: false,
      year: "2025",
      fullTitle: "벨리곰 x 호두정과 3종 콜라보 패키지",
      desc: ["롯데홈쇼핑 인기 IP '벨리곰'과의 라이선스 협업 프로젝트로, 호두정과 3종·그래놀라 2종 총 5종을 단일 캐릭터 시스템 안에서 전개해야 하는 과제였습니다. 라이선스 가이드라인을 준수하면서도 제품별 개성을 잃지 않아야 했고, 혼잡한 오프라인 매대와 온라인 상세페이지라는 서로 다른 접점에서 동일한 브랜드 경험을 유지해야 했습니다.",
            "벨리곰의 캐릭터 포즈는 5종 전체에 동일하게 적용해 하나의 시스템임을 즉각 인지시키고, 캐릭터가 직접 들고 있는 소품을 인절미·초코·카라멜 등 실제 맛으로 구성해 제품별 컬러와 함께 맛을 직관적으로 구분할 수 있도록 설계했습니다.",
            "로고 배치와 컬러 프레임 규격을 고정해 개별 제품이 아닌 하나의 세트로 인지되도록 시스템화했으며, 오프라인 매대의 시선 점유뿐 아니라 자사몰 상세페이지까지 직접 디자인해 온라인 구매 여정에서도 동일한 캐릭터 경험이 이어지도록 확장했습니다.",],
      tags: ["Branding", "Identity", "Collaboration", "Character", "Contribution · 100%"],
    },
    {
      id: 2,
      cat: "BX",
      genre: "Character",
      title: "Packaging Design",
      thumbnail: "/images/thumbnail_seasoning_ms.png",
      img: "/images/seasoning_ms_ds.png",
      bg: "#C4B8C4",
      isVideo: false,
      year: "2024",
      fullTitle: "신규 브랜드 캐릭터 '시즈닝몬스터' 개발",
      desc: ["기기존 시즈닝 아몬드 시리즈의 캐릭터가 노후화되어 리프레시가 필요한 상황이었습니다.",
            "기존 캐릭터의 정체성을 유지한 리터치 안과, 완전히 새로운 캐릭터를 개발하는 안 두 가지를 제안했습니다. 신규 안은 시즈닝 맛에 따라 입술 색이 변하는 설정을 부여해, 캐릭터 자체가 맛 구분 기능까지 겸하도록 설계했습니다. 5가지 맛을 각각의 컬러와 표정으로 구분해, 소비자가 패키지만 봐도 맛을 직관적으로 인지하도록 했습니다.",
            "최종적으로는 기존 브랜드 자산과의 연속성을 고려해 리터치 안이 채택되었습니다.",
            "시즈닝몬스터 안은 이번엔 채택되지 않았지만, 향후 신규 라인이나 세컨더리 브랜드 개발 시 활용 가능한 캐릭터 자산으로 보유하고 있습니다.",],
      tags: ["Character", "BX", "Packaging", "Storytelling", "Monster", "Contribution · 100%"],
    },
    {
      id: 3,
      cat: "GRAPHIC DESIGN",
      genre: "Food",
      title: "Digital Design",
      thumbnail: "/images/thumbnail_bellygom_web_01.png",
      img: "/images/2026_Bellygom.jpeg",
      bg: "#C4C0B8",
      isVideo: false,
      year: "2026",
      fullTitle: "벨리곰 호두정과 이커머스 상세페이지",
      desc: ["설 선물세트 구성 상세페이지로, 소개해야 할 정보량이 많은 만큼(패키지 사이즈, 구성품별 맛, 정보고시 등) 벨리곰 캐릭터를 각 섹션의 안내자로 배치해 정보 단위를 시각적으로 분절하고 지루하지 않게 읽히도록 설계했습니다.",
            "새해 인사 → 구성품 소개 → 맛별 상세 → 정보고시 → 라이선스 순으로 흐름을 짜, 선물을 고르고 확인하는 실제 구매 여정을 그대로 따라가도록 구성했습니다.",],
      tags: ["Digital Design", "E-commerce", "UI/UX", "Visual Merchandising", "Contribution · 100%"],
    },
    {
      id: 4,
      cat: "VIDEOGRAPHY",
      genre: "Ads",
      title: "40th Campaign",
      thumbnail: "/images/thumbnail_40th.png",
      img: "/images/project5.png",
      video: "/videos/40th.mp4",
      bg: "#B8C0C8",
      isVideo: true,
      year: "2026",
      fullTitle: "머거본 40주년 기념 캠페인 (AI Full Production)",
      desc: ["홈페이지 리뉴얼 과정에서 브랜드 영상이 필요했고, 마침 올해가 브랜드 40주년이라는 점에서 헤리티지와 미래 비전을 함께 담은 캠페인으로 기획을 확장했습니다.",
            "별도 외주 프로덕션 없이 내부에서 소화해야 하는 상황이었고, 생성형 AI 기술이 실무에 바로 활용 가능한 수준으로 발전했다고 판단해 이를 직접 검증해보는 방향을 택했습니다. 예산 제약을 새로운 제작 워크플로우를 실험하는 기회로 전환한 프로젝트입니다.",
            "프랑스 유학 시절 사진·영상 전공을 통해 익힌 콘티 구성 능력을 바탕으로 전체 흐름을 설계했습니다. 내용 기획 → 기획에 맞는 썸네일 이미지 생성 → 이미지 기반 영상 생성 → 편집 → 오디오·내레이션 생성까지 전 과정을 AI 툴을 활용해 혼자 디렉팅했습니다.",
            "브랜드 헤리티지를 트렌디한 감각으로 재해석하는 동시에, 실무 제작 프로세스에 생성형 AI를 접목하는 새로운 워크플로우를 직접 검증했습니다.",],
      tags: ["AI Video", "Campaign", "Creative Directing", "Storyboard", "Contribution · 100%"],
    },
    {
      id: 5,
      cat: "VIDEOGRAPHY",
      genre: "Brand Film",
      title: "Music Video",
      thumbnail: "/images/thumbnail_nuts_for_u.png",
      img: "/images/project6.png",
      video: "/videos/Nuts_for_U.mp4",
      bg: "#C0C8BC",
      isVideo: true,
      year: "2026",
      fullTitle: "'너츠포유' 일상 밀착형 브랜드 필름",
      desc: ["데일리 너츠포유 4종 출시 시점에, 별도 마케팅 캠페인 없이도 브랜드를 각인시킬 콘텐츠가 필요했습니다.",
            "하루견과, 먼투썬 등 경쟁 브랜드들이 이미 '하루', '월요일부터 일요일'이라는 시간에 대한 특정 단어를 선점하고 있다는 점에 착안해, 정면 대결 대신 일상중의 시간대를 각 제품에 나눠 배정하는 전략을 세웠습니다. 4개 맛이 각각 다른 시간·상황을 점유하면, 결과적으로 '너츠포유'가 하루 전체를 커버하는 브랜드로 인지되도록 설계했습니다.",
            "예를 들어 '데일리 너츠포유'는 점심 직후 나른한 오후 2시, 짝사랑하는 상대에게 마음을 전하는 이야기에 'I'm Nuts For You'라는 브랜드 문장을 자연스럽게 녹인 가사로 풀었습니다. 나머지 3개 맛도 각각 아침·오전·밤이라는 다른 시간대의 상황과 노래에 브랜드명을 반복 삽입해, 4편이 모여 하루 전체의 타임라인을 구성하도록 만들었습니다. 노래를 들으며 가사를 따라 읽도록 노래방 자막 형식을 적용해, 청각(멜로디)과 시각(가사) 양쪽에서 브랜드명이 각인되도록 설계했습니다.",
            "별도 광고 없이 콘텐츠 자체의 구조(시간대 선점 + 반복 각인 장치)로 브랜드 인지를 유도하는 자체 마케팅 필름 4편을 기획부터 제작까지 단독으로 완성했습니다.",],
      tags: ["Brand Film", "TPO Strategy", "Directing", "Music Video", "Contribution · 100%"],
    },
    {
      id: 6,
      cat: "PHOTOGRAPHY",
      genre: "Commercial",
      title: "Product",
      thumbnail: "/images/thumbnail_ads_01.png",
      img: "/images/photo_ads_00.png",
      bg: "#C8C8C0",
      isVideo: false,
      year: "2019",
      fullTitle: "상업용 커머셜 및 프로덕트 포토그래피",
      desc: ["프랑스 유학 시절 외국인으로서 마주한 차별의 경험에서 출발해, '겉모습 때문에 배척당하지만 실제로는 우리와 다르지 않은 삶을 살아가는 존재'라는 주제를 다루고 싶었습니다. 공룡을 그 은유로 설정하고, 여러 상업 사진 컨셉 안에 반복적으로 등장시키는 개인 연작 프로젝트를 진행했습니다.",
            "유리의 청결함을 표현하는 블루 톤의 미니어처 도시 세계관 속에, 사람들 틈에서 일하며 살아가는 작은 존재로 공룡을 배치했습니다.",
            "초콜릿 원료가 자연에서 채집된다는 이미지를 미니어처 숲으로 구현하고, 그 안에 자연스럽게 녹아든 공룡을 통해 낯선 존재도 결국 같은 자연·환경을 공유한다는 메시지를 담았습니다.",
            "두 작업 모두 빛의 각도와 반사, 미니어처와 실물 소재 간의 스케일감을 정밀하게 컨트롤해 각기 다른 브랜드 톤 안에서도 하나의 세계관처럼 보이도록 완성했습니다.",],
      tags: ["Commercial", "Lighting", "Product Photo", "Texture", "Contribution · 100%"],
    },
    {
      id: 7,
      cat: "PHOTOGRAPHY",
      genre: "Fashion",
      title: "Editorial",
      thumbnail: "/images/thumbnail_fashion_00.png",
      img: "/images/photo_fashion_00.png",
      bg: "#C4C0C8",
      isVideo: false,
      year: "2020",
      fullTitle: "패션 에디토리얼: 다양성의 미학",
      desc: ["프랑스 유학 시절, 다양한 배경을 가진 인물들이 정형화된 미의 기준 밖에서 어떻게 자신만의 개성을 드러내는지에 관심을 갖고 진행한 에디토리얼 프로젝트입니다.",
            "하나의 톤으로 통일하기보다, 인물마다 어울리는 배경과 무드를 다르게 설계했습니다. 강렬한 컬러 배경의 스트리트 룩, 도시 건축을 배경으로 한 실루엣 컷, 자연광 아래의 클로즈업 뷰티 샷, 필드에서의 자연스러운 자세까지 — 각 인물이 가진 개성에 맞춰 촬영 방식 자체를 다르게 가져갔습니다.",
            "사회적 편견 없이 자신을 자유롭게 표현할 수 있는 환경에 대한 지지를, 정형화되지 않은 다양한 시각 언어로 기록했습니다.",],
      tags: ["Editorial", "Fashion", "Art Direction", "Diversity", "Paris", "Contribution · 100%"],
    },
  ],

  /* ── 타임라인 (최신순) */
  timeline: [
    {
      id: 0,
      role: "BX 패키지 디자이너",
      type: "Professional",
      company: "머거본 | 세계식품(주)",
      loc: "대한민국",
      period: "2023 - 현재",
      dur: "2.11년",
      dot: true,
      detail:
        "머거본의 주력 제품(견과, 육포 등) 패키지 리뉴얼 및 BI 구축을 통해 브랜드 신뢰도를 강화하고 인지도를 상승시켰습니다. 단순히 패키지 제작에 그치지 않고, 온라인 상세페이지 리뉴얼, 홈페이지 리뉴얼을 병행하여 구매 전환율 상승과 매출 증대에 간접적으로 기여했습니다. 주니어 패키지 디자이너로서 인쇄 감리부터 현장 품질 관리까지 책임지며, 고객에게 일관되고 차별화된 브랜드 아이덴티티를 전달하고자 노력하고 있습니다.",
      tags: [
        "Brand Identity System",
        "Package Solution",
        "CMYK",
        "Post-press",
        "BX Strategy",
      ],
    },
    {
      id: 1,
      role: "포토그래퍼",
      type: "Freelance",
      company: "Fashion & Commercial Photography / Ex. Monoprix online",
      loc: "프랑스, 스페인, 대한민국",
      period: "2019 - 2023",
      dur: "5년",
      dot: false,
      detail:
        "프랑스 유통 대기업 Monoprix Online의 제품 사진 및 브랜드 캠페인을 담당하며 상업 비주얼의 정교함을 익혔습니다. 무드보드 기획부터 라이팅, 후반 보정까지 전 과정을 참여하며 '브랜드의 가치를 극대화하는 이미지'를 생산했습니다. 이때 확립한 높은 비주얼 감도는 현재 패키지와 디지털 매체를 아우르는 일관된 브랜드 경험(BX) 설계의 핵심 자산입니다.",
      tags: [
        "Fashion Photo",
        "Commercial",
        "Monoprix",
        "Europe",
        "Art Directing",
        "High-end Visual",
      ],
    },
    {
      id: 2,
      role: "그래픽 디자인 & 사진학",
      type: "Bachelor's degree",
      company: "ECOLE STUDIO CREA PARIS & SPEOS PARIS",
      loc: "프랑스 파리",
      period: "2016 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리 ECOLE STUDIO CREA(그래픽)와 SPEOS PARIS(사진)에서 복수 전공하며 디자인 이론과 시각 구현 능력을 체계적으로 훈련했습니다. 디자인 기획부터 최종 비주얼 제작까지 전 과정을 핸들링할 수 있는 '하이브리드 디자이너'로서의 역량을 갖추었으며, 졸업 작품전 참여를 통해 글로벌 수준의 크리에이티브 감각을 증명했습니다.",
      tags: [
        "Graphic Design",
        "Photography",
        "Paris School",
        "Grand Ecole",
        "Design Theory",
        "Fine Art",
      ],
    },
    {
      id: 3,
      role: "프랑스 유학",
      type: "Global Mind",
      company: "Fine Art & Fashion Marketing",
      loc: "프랑스 파리",
      period: "2012 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리에서 약 10년간 파인아트와 패션 마케팅을 전공하며 유럽 크리에이티브 씬의 정점을 경험했습니다. 단순히 시각적 아름다움을 넘어, 브랜드가 소비자와 감성적으로 연결되는 '비주얼 스토리텔링'의 힘을 체득했습니다. 박물관과 갤러리에서 익힌 고전 미술의 비례감과 현대 디자인의 맥락은 현재 제가 전개하는 모든 BX 디자인의 독보적인 미적 근간이 되었습니다.",
      tags: [
        "European Aesthetics",
        "Visual Storytelling",
        "Global Experience",
        "Paris",
        "Fashion Marketing",
        "Fine Art",
      ],
    },
  ],

  /* ── 챗봇 Q&A */
  chatbot: {
    greeting: '"궁금하신 점이 있다면 무엇이든 물어보세요!"',
    questions: [
      {
        q: "왜 CJ제일제당 전략디자인센터 Brand & Package Designer\n 채용에 지원하게 되었나요?",
        a:[
          "브랜드가 국경을 넘어 성장하려면, 현지 소비자에게는 '내 것'처럼 느껴지면서도 본사의 정체성은 흔들리지 않아야 한다고 생각합니다. 프랑스에서 10년을 살며 한국 문화가 글로벌 시장에 자리 잡는 과정을 직접 지켜봤습니다. 유학 초기 한국은 낯선 나라였지만, 콘텐츠를 통해 문화적 관심이 쌓이면서 결국 한국 음식을 직접 시도해보고 싶다는 욕구로 이어지는 걸 봤습니다. 그 관심을 실제 구매로 연결시키는 마지막 접점이 바로 패키지라고 생각합니다.",
          "현재 회사에서는 국내용과 별도로 수출용 패키지를 제작하고 있지만, ODM 구조 특성상 벤더사가 요구하는 규격과 형식을 따르는 데 그치고 있어 브랜드 자체의 일관된 축을 설계할 기회는 제한적이었습니다. 이 과정에서 오히려 명확히 느낀 건, 여러 국가·벤더사를 상대하면서도 브랜드의 정체성이 흐트러지지 않으려면 그걸 지켜내는 전략과 거버넌스가 반드시 별도로 필요하다는 점이었습니다. CJ제일제당 전략디자인센터가 '글로벌 BA와의 협업을 통한 브랜드 디자인 거버넌스', '국가별 디자인 검토·협업 프로세스'를 명시적으로 운영하고 있다는 점이, 제가 현재 환경에서 느낀 필요를 실제로 실행할 수 있는 조직이라고 판단한 이유입니다.",
          "또한 라이선스 IP 콜라보를 진행하며 외부 가이드라인을 준수하는 동시에 자사 브랜드 자산을 함께 지켜내는 감각을 쌓았고, 패키지 리뉴얼과 씨즐 촬영, 인쇄 감리·품질 관리까지 디자인 실행 전 과정을 직접 다뤄왔습니다. 브랜드 방향성에 맞춰 키비주얼과 그래픽 에셋을 개발하고, 결과물의 품질까지 책임지는 이 역할이 Design Creative가 요구하는 실행력과 맞닿아 있다고 생각합니다.",
          "제품의 본질은 결국 맛과 품질이고, 디자인은 그것을 세계 각지의 소비자에게 올바르게 소개하고 신뢰를 쌓게 하는 매개체라고 믿습니다. CJ제일제당의 브랜드들이 각 시장에서 '그 나라 브랜드처럼' 자연스럽게 받아들여지면서도, 결국 하나의 목소리로 기억되도록 만드는 데 기여하고 싶어 지원하게 되었습니다.",],
      },
      {
        q: "프랑스 유학부터 패키징, 브랜드 영상까지\n다양한 경험이 디자인에 어떤 시각을 만들어줬나요?",
        a: ["프랑스에서의 시간과 패션 포토그래피 디렉팅 경험이 제게 남긴 건 특정 툴의 숙련도가 아니라, 현장에서 단련된 비주얼 감도입니다. 좋은 디자인이 왜 좋은지를 언어화할 수 있는 능력, 레퍼런스의 맥락을 읽는 눈. 이런 감각은 패키징이든 영상이든 브랜딩이든, 카테고리를 넘어 작동한다고 생각합니다.",
            "그 감도를 바탕으로 지금은 패키지 디자인부터 브랜드 영상까지 다양한 매체를 다루고 있습니다. 어떤 매체를 쓰든 결국 브랜드가 고객에게 가장 매력적이고 직관적으로 닿을 수 있는 방법을 찾는 것. 그게 제가 디자인에서 가장 중요하게 생각하는 지점입니다.",
            ],
      },
      {
        q: "브랜드 디자이너로서 유관 부서와 협업할 때\n 본인만의 방식이 있다면요?",
        a: ["디자인은 개인의 작품 활동이 아니라, 다양한 부서와 시너지를 내어 비즈니스적 성과를 만들어내는 과정이라고 생각합니다.",
            "실제로 패키징 작업을 하면서 품질팀, 영업팀과 긴밀하게 소통할 일이 많았습니다. 디자이너 눈에는 안 보이던 부분을 영업팀이 짚어주고, 반대로 제가 브랜드 관점에서 놓친 부분을 잡아주기도 했습니다. 수정이 오갈수록 결과물이 더 단단해진다는 걸 경험으로 배웠습니다.",
            "그래서 제 협업의 핵심은 서로의 전문성을 존중하고 각자의 강점을 연결하는 것입니다. 원활한 소통과 신뢰를 바탕으로, 브랜드가 최고의 성과를 낼 수 있도록 돕는 유기적인 파트너가 되겠습니다.",
            ],
      },
   {
        q: "이 포트폴리오 웹앱은 Claude AI로\n 직접 바이브 코딩해서 만드셨다고요?",
        a: [
          "네, 맞습니다! 기획부터 컴포넌트 설계까지 Claude AI를 활용하고, CodeSandbox · GitHub · Vercel을 거쳐 직접 배포까지 완료했습니다. 남들처럼 똑같이 PDF 포트폴리오를 내기보다, AI를 활용해 직접 웹으로 구축하는 것이 제 기획과 실행력을 가장 직관적으로 보여주는 방식이라 판단했습니다.",
          "최근 AI 기술이 발전하면서 디자이너가 통제할 수 있는 전문 영역의 바운더리가 무한히 넓어지고 있다고 생각합니다. 생각보다 툴 활용이 직관적이고 어렵지 않았고, 도구를 가리지 않고 제가 원하는 비주얼을 끝까지 구현해 내는 좋은 경험이 되었습니다. 앞으로도 AI 툴을 적극적으로 활용해 제가 제안할 수 있는 BX의 영역을 계속 넓혀갈 계획입니다.",
        ],
      },
    ],
  },
};
