// ═══════════════════════════════════════════════════
//  data.js  — 모든 콘텐츠 데이터 (여기서 한 번에 수정)
// ═══════════════════════════════════════════════════

export const D = {
  /* ── 브랜드 */
  brand: {
    name: "DesignLab",
    tagline: "Crafting Brand Experience", // Arbutus 폰트
    subTagline: "비즈니스를 완성하는 여정", // Ycomputer 폰트
    copyright: "@2026 DESIGNLAB",
    author: "by KWAK SUN HEE",
    logoImg: "/images/dl_logo.png",
  },

  /* ── 프로필 */
  profile: {
    name: "곽선희 / Murgerbon",
    role: "Visual Junior Director · Packaging Designer",
    memojiImg: "/images/mypage_memoticon.png",
    chatMemojiImg: "/images/chatbot_online.png",
    chatGreetImg: "/images/chatbot_memoticon_01.png",
    chatBotBubbleImg: "/images/chatbot_memoticon_02.png",
    chatYouImg: "/images/chatbot_you.png",
    chatImg: "/images/chat.png",
    stats: [
      { value: "10+", label: "France Study" },
      { value: "2.7+", label: "Practice" },
      { value: "3", label: "Language" },
    ],
    languages: "KR / FR / EN",
    expertise: ["BX Strategy", "Package Production", "Art Direction"],
    philosophy: {
      title: "The Art of Logic :",
      subtitle: "논리로 빚어낸 브랜드의 격",
    },
  },

  /* ── 대시보드 */
  dashboard: {
    title: "The Art of Logic",
    subtitle: ": BX Synergy Report",
    desc: "10년의 글로벌 미학과 비즈니스 로직을 연결하여\n기업의 실질적 가치를 설계합니다.",
    filterTabs: ["BX", "Visual Dir.", "Production", "Digital/Ai"],
    skills: [
      {
        name: "Visual Communication",
        pct: 90,
        sub: "Brand Identity Design : Logo, Typography, Brand Guideline",
        detail: "타겟 분석 기반의 브랜드 정체성 확립 및 시각화",
        cat: "BX",
      },
      {
        name: "Photography & Videography",
        pct: 100,
        sub: "Commercial Photo, Film Directing, Lighting",
        detail: "비주얼 톤앤매너 (사진 & 영상) 디렉팅",
        cat: "Visual Dir.",
      },
      {
        name: "Packaging Production Mgmt",
        pct: 100,
        sub: "CMYK Color Control, Post-press, Inspection",
        detail: "정교한 도수 관리 및 현장 인쇄 감리를 통한 구현력 최적화",
        cat: "Production",
      },
      {
        name: "AI & Digital Tools",
        pct: 78,
        sub: "Figma, Midjourney, Vibe Coding, Prompt Engineering",
        detail: "AI 바이브 코딩 레버리지 및 디지털 워크플로우 최적화",
        cat: "Digital/Ai",
      },
    ],
    chartBars: [
      { label: "BX", orange: 65, teal: 80 },
      { label: "Visual", orange: 90, teal: 100 },
      { label: "Pack.", orange: 45, teal: 60 },
      { label: "Prod.", orange: 80, teal: 100 },
      { label: "Digital", orange: 50, teal: 70 },
      { label: "Ai", orange: 70, teal: 78 },
    ],
  },

  /* ── 포트폴리오 (8개) */
  projects: [
    {
      id: 0,
      cat: "PACKAGING",
      genre: "Food",
      title: "Renewal",
      thumbnail: "/images/thumbnail_jerky.png",
      img: "/images/photo_jerky.png",
      bg: "#C8C4B8",
      isVideo: false,
      year: "2025",
      fullTitle: "머거본 육포 라인업 패밀리룩 리뉴얼",
      desc: "육포의 근본인 '본육포' 시리즈를 중심으로, 파편화되어 있던 기존 패키지들을 하나의 통합된 비주얼 시스템으로 재정립했습니다. 브랜드 헤리티지를 유지하면서도 현대적인 감각의 패밀리룩을 구현하여 브랜드 인지도를 강화했습니다.",
      tags: ["Package Design", "Renewal", "Visual Strategy", "Family-look"],
    },
    {
      id: 1,
      cat: "PACKAGING",
      genre: "Food",
      title: "Brand Identity",
      thumbnail: "/images/thumbnail_bellygom.png",
      img: "/images/belly_gom.png",
      bg: "#B8C4C0",
      isVideo: false,
      year: "2025",
      fullTitle: "벨리곰 x 호두정과 3종 콜라보 패키지",
      desc: "'벨리곰' 캐릭터의 친근함과 프리미엄 호두정과의 만남을 시각화한 프로젝트. 3가지 맛의 개성을 살리면서도 캐릭터를 눈에 띄게 배치하여, 혼잡한 오프라인 매대에서 시선 점유를 유도했습니다.",
      tags: ["Branding", "Identity", "Collaboration", "Character"],
    },
    {
      id: 2,
      cat: "BX",
      genre: "Character",
      title: "Packaging Design",
      thumbnail: "/images/thumbnail_seasoning_ms.png",
      img: "/images/seasoning_ms_ds.png",
      bg: "#C4B8C4",
      isVideo: false,
      year: "2024",
      fullTitle: "신규 브랜드 캐릭터 '시즈닝몬스터' 개발",
      desc: "기존 정형화된 캐릭터에서 탈피하여, 시즈닝의 맛에 따라 입술 색이 변하는 위트 있는 설정의 '시즈닝몬스터'를 개발했습니다. 캐릭터의 특징을 패키지 전면에 녹여내어 고객에게 감성적이고 즐거운 브랜드 경험(BX)을 제공합니다.",
      tags: ["Character", "BX", "Packaging", "Storytelling", "Monster"],
    },
    {
      id: 3,
      cat: "GRAPHIC DESIGN",
      genre: "Food",
      title: "Digital Design",
      thumbnail: "/images/thumbnail_bellygom_web_01.png",
      img: "/images/2026_Bellygom.jpeg",
      bg: "#C4C0B8",
      isVideo: false,
      year: "2026",
      fullTitle: "벨리곰 호두정과 이커머스 상세페이지",
      desc: "디지털 환경에서 벨리곰의 매력을 극대화하여 구매 전환율을 높이는 상세페이지를 설계했습니다. 직관적인 비주얼 그리드와 데이터 기반의 워크플로우를 통해 제품의 핵심 셀링 포인트를 효과적으로 전달하는 디지털 경험을 구현했습니다.",
      tags: ["Digital Design", "E-commerce", "UI/UX", "Visual Merchandising"],
    },
    {
      id: 4,
      cat: "VIDEOGRAPHY",
      genre: "Ads",
      title: "40th Campaign",
      thumbnail: "/images/thumbnail_40th.png",
      img: "/images/project5.png",
      video: "/videos/40th.mp4",
      bg: "#B8C0C8",
      isVideo: true,
      year: "2026",
      fullTitle: "머거본 40주년 기념 캠페인 (AI Full Production)",
      desc: "브랜드의 40년 역사와 미래 비전을 담은 광고 캠페인. 기획부터 스토리보드, 음악, 내레이션, 영상 생성까지 전 과정을 AI(Generative AI)로 제작했습니다. 최신 기술 레버리지를 통해 브랜드 헤리티지를 트렌디한 감각으로 재해석했습니다.",
      tags: ["AI Video", "Campaign", "Creative Directing", "Future Vision"],
    },
    {
      id: 5,
      cat: "VIDEOGRAPHY",
      genre: "Brand Film",
      title: "Music Video",
      thumbnail: "/images/thumbnail_nuts_for_u.png",
      img: "/images/project6.png",
      video: "/videos/Nuts_for_U.mp4",
      bg: "#C0C8BC",
      isVideo: true,
      year: "2026",
      fullTitle: "'너츠포유' 일상 밀착형 브랜드 필름",
      desc: "학교, 집, 직장 등 소비자의 실제 TPO(Time·Place·Occasion)에 맞춰 제작된 브랜드 필름. 평범한 일상의 순간마다 '너츠포유'가 함께한다는 메시지를 각기 다른 음악과 영상미로 표현하여 브랜드의 일상 점유율을 높이고자 했습니다.",
      tags: ["Brand Film", "TPO Strategy", "Directing", "Music Video"],
    },
    {
      id: 6,
      cat: "PHOTOGRAPHY",
      genre: "Commercial",
      title: "Product",
      thumbnail: "/images/thumbnail_ads_01.png",
      img: "/images/photo_ads_00.png",
      bg: "#C8C8C0",
      isVideo: false,
      year: "2019",
      fullTitle: "상업용 커머셜 및 프로덕트 포토그래피",
      desc: "제품 고유의 질감과 조형미를 극대화하기 위해 빛의 각도와 반사를 정밀하게 컨트롤했습니다. 매체별 특성에 최적화된 비주얼 톤을 도출하여 제품이 가진 프리미엄 가치를 시각적으로 증명한 프로젝트입니다.",
      tags: ["Commercial", "Lighting", "Product Photo", "Texture"],
    },
    {
      id: 7,
      cat: "PHOTOGRAPHY",
      genre: "Fashion",
      title: "Editorial",
      thumbnail: "/images/thumbnail_fashion_00.png",
      img: "/images/photo_fashion_00.png",
      bg: "#C4C0C8",
      isVideo: false,
      year: "2020",
      fullTitle: "패션 에디토리얼: 다양성의 미학",
      desc: "프랑스 유학 시절 진행한 에디토리얼 프로젝트. 다양한 스타일의 인물을 통해 개인의 고유한 아름다움과 독창성을 포착했습니다. 사회적 편견을 넘어, 각 개인이 자신을 자유롭게 표현할 수 있는 환경에 대한 지지를 시각적 서사로 기록했습니다.",
      tags: ["Editorial", "Fashion", "Art Direction", "Diversity", "Paris"],
    },
  ],

  /* ── 타임라인 (최신순) */
  timeline: [
    {
      id: 0,
      role: "BX 패키지 디자이너",
      type: "Professional",
      company: "머거본 | 세계식품(주)",
      loc: "대한민국",
      period: "2023 - 현재",
      dur: "2.7년",
      dot: true,
      detail:
        "머거본의 주력 제품(견과, 육포 등) 패키지 리뉴얼 및 BI 구축을 통해 브랜드 신뢰도를 강화하고 인지도를 상승시켰습니다. 단순히 패키지 제작에 그치지 않고, 온라인 상세페이지 리뉴얼, 홈페이지 리뉴얼을 병행하여 구매 전환율 상승과 매출 증대에 간접적으로 기여했습니다. 주니어 패키지 디자이너로서 인쇄 감리부터 현장 품질 관리까지 책임지며, 고객에게 일관되고 차별화된 브랜드 아이덴티티를 전달하고자 노력하고 있습니다.",
      tags: [
        "Brand Identity System",
        "Package Solution",
        "CMYK",
        "Post-press",
        "BX Strategy",
      ],
    },
    {
      id: 1,
      role: "포토그래퍼",
      type: "Freelance",
      company: "Fashion & Commercial Photography / Ex. Monoprix online",
      loc: "프랑스, 스페인, 대한민국",
      period: "2019 - 2023",
      dur: "5년",
      dot: false,
      detail:
        "프랑스 유통 대기업 Monoprix Online의 제품 사진 및 브랜드 캠페인을 담당하며 상업 비주얼의 정교함을 익혔습니다. 무드보드 기획부터 라이팅, 후반 보정까지 전 과정을 참여하며 '브랜드의 가치를 극대화하는 이미지'를 생산했습니다. 이때 확립한 높은 비주얼 감도는 현재 패키지와 디지털 매체를 아우르는 일관된 브랜드 경험(BX) 설계의 핵심 자산입니다.",
      tags: [
        "Fashion Photo",
        "Commercial",
        "Monoprix",
        "Europe",
        "Art Directing",
        "High-end Visual",
      ],
    },
    {
      id: 2,
      role: "그래픽 디자인 & 사진학",
      type: "Bachelor's degree",
      company: "ECOLE STUDIO CREA PARIS & SPEOS PARIS",
      loc: "프랑스 파리",
      period: "2016 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리 ECOLE STUDIO CREA(그래픽)와 SPEOS PARIS(사진)에서 복수 전공하며 디자인 이론과 시각 구현 능력을 체계적으로 훈련했습니다. 디자인 기획부터 최종 비주얼 제작까지 전 과정을 핸들링할 수 있는 '하이브리드 디자이너'로서의 역량을 갖추었으며, 졸업 작품전 참여를 통해 글로벌 수준의 크리에이티브 감각을 증명했습니다.",
      tags: [
        "Graphic Design",
        "Photography",
        "Paris School",
        "Grand Ecole",
        "Design Theory",
        "Fine Art",
      ],
    },
    {
      id: 3,
      role: "프랑스 유학",
      type: "Global Mind",
      company: "Fine Art & Fashion Marketing",
      loc: "프랑스 파리",
      period: "2012 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리에서 약 10년간 파인아트와 패션 마케팅을 전공하며 유럽 크리에이티브 씬의 정점을 경험했습니다. 단순히 시각적 아름다움을 넘어, 브랜드가 소비자와 감성적으로 연결되는 '비주얼 스토리텔링'의 힘을 체득했습니다. 박물관과 갤러리에서 익힌 고전 미술의 비례감과 현대 디자인의 맥락은 현재 제가 전개하는 모든 BX 디자인의 독보적인 미적 근간이 되었습니다.",
      tags: [
        "European Aesthetics",
        "Visual Storytelling",
        "Global Experience",
        "Paris",
        "Fashion Marketing",
        "Fine Art",
      ],
    },
  ],

  /* ── 챗봇 Q&A */
  chatbot: {
    greeting: '"궁금하신 점이 있다면 무엇이든 물어보세요!"',
    questions: [
      {
        q: "패키지 디자인에서 BX 디자인으로,\n어떤 계기로 방향을 넓히게 됐나요?",
        a:[
          "패키지 디자인을 하면서 자연스럽게 BX 전체로 시야가 넓어졌습니다. 중소기업 인하우스 환경에서는 패키지 하나를 만들더라도 브랜드가 고객과 만나는 모든 접점을 함께 고려해야 했거든요. 제품을 처음 인식하는 순간부터 구매 후까지, 일관된 감각으로 브랜드가 말을 걸어야 한다는 걸 실무에서 직접 체감했습니다.",
          "입사 후 팀 구성이 새로 바뀌면서 브랜드 방향성을 처음부터 함께 만들어가는 경험도 했습니다. 그 과정에서 패키지 디자인은 BX의 한 접점일 뿐이고, 결국 브랜드 경험 전체를 설계하는 일이 더 본질적이라는 걸 알게 됐습니다.",
          "B2B든 B2C든, 업종에 관계없이 BX는 항상 필요합니다. 지금도 패키지 디자인을 하고 있지만, 스스로는 BX 디자인을 하고 있다고 생각합니다.",
          ],
      },
      {
        q: "프랑스 유학부터 패키징, 브랜드 영상까지\n다양한 경험이 디자인에 어떤 시각을 만들어줬나요?",
        a: ["프랑스에서의 시간과 패션 포토그래피 디렉팅 경험이 제게 남긴 건 특정 툴의 숙련도가 아니라, 현장에서 단련된 비주얼 감도입니다. 좋은 디자인이 왜 좋은지를 언어화할 수 있는 능력, 레퍼런스의 맥락을 읽는 눈. 이런 감각은 패키징이든 영상이든 브랜딩이든, 카테고리를 넘어 작동한다고 생각합니다.",
            "그 감도를 바탕으로 지금은 패키지 디자인부터 브랜드 영상까지 다양한 매체를 다루고 있습니다. 어떤 매체를 쓰든 결국 브랜드가 고객에게 가장 매력적이고 직관적으로 닿을 수 있는 방법을 찾는 것. 그게 제가 디자인에서 가장 중요하게 생각하는 지점입니다.",
            ],
      },
      {
        q: "브랜드 디자이너로서 유관 부서와 협업할 때\n 본인만의 방식이 있다면요?",
        a: ["디자인은 개인의 작품 활동이 아니라, 다양한 부서와 시너지를 내어 비즈니스적 성과를 만들어내는 과정이라고 생각합니다.",
            "실제로 패키징 작업을 하면서 품질팀, 영업팀과 긴밀하게 소통할 일이 많았습니다. 디자이너 눈에는 안 보이던 부분을 영업팀이 짚어주고, 반대로 제가 브랜드 관점에서 놓친 부분을 잡아주기도 했습니다. 수정이 오갈수록 결과물이 더 단단해진다는 걸 경험으로 배웠습니다.",
            "그래서 제 협업의 핵심은 서로의 전문성을 존중하고 각자의 강점을 연결하는 것입니다. 원활한 소통과 신뢰를 바탕으로, 브랜드가 최고의 성과를 낼 수 있도록 돕는 유기적인 파트너가 되겠습니다.",
            ],
      },
   {
        q: "이 포트폴리오 웹앱은 Claude AI로\n 직접 바이브 코딩해서 만드셨다고요?",
        a: [
          "네, 맞습니다! 기획부터 컴포넌트 설계까지 Claude AI를 활용하고, CodeSandbox · GitHub · Vercel을 거쳐 직접 배포까지 완료했습니다. 남들처럼 똑같이 PDF 포트폴리오를 내기보다, AI를 활용해 직접 웹으로 구축하는 것이 제 기획과 실행력을 가장 직관적으로 보여주는 방식이라 판단했습니다.",
          "최근 AI 기술이 발전하면서 디자이너가 통제할 수 있는 전문 영역의 바운더리가 무한히 넓어지고 있다고 생각합니다. 생각보다 툴 활용이 직관적이고 어렵지 않았고, 도구를 가리지 않고 제가 원하는 비주얼을 끝까지 구현해 내는 좋은 경험이 되었습니다. 앞으로도 AI 툴을 적극적으로 활용해 제가 제안할 수 있는 BX의 영역을 계속 넓혀갈 계획입니다.",
        ],
      },
    ],
  },
};
