// ═══════════════════════════════════════════════════
//  data.js  — 모든 콘텐츠 데이터 (여기서 한 번에 수정)
// ═══════════════════════════════════════════════════

export const D = {
  /* ── 브랜드 */
  brand: {
    name: "DesignLab",
    tagline: "Crafting Brand Experience", // Arbutus 폰트
    subTagline: "비즈니스를 완성하는 여정", // Ycomputer 폰트
    copyright: "@2026 DESIGNLAB",
    author: "by KWAK SUN HEE",
    logoImg: "/images/dl_logo.png",
  },

  /* ── 프로필 */
  profile: {
    name: "곽선희 / Murgerbon",
    role: "Visual Junior Director · Packaging Designer",
    memojiImg: "/images/mypage_memoticon.png",
    chatMemojiImg: "/images/chatbot_online.png",
    chatGreetImg: "/images/chatbot_memoticon_01.png",
    chatBotBubbleImg: "/images/chatbot_memoticon_02.png",
    chatYouImg: "/images/chatbot_you.png",
    chatImg: "/images/chat.png",
    stats: [
      { value: "10+", label: "France Study" },
      { value: "2.7+", label: "Practice" },
      { value: "3", label: "Language" },
    ],
    languages: "KR / FR / EN",
    expertise: ["BX Strategy", "Package Production", "Art Direction"],
    philosophy: {
      title: "The Art of Logic :",
      subtitle: "논리로 빚어낸 브랜드의 격",
    },
  },

  /* ── 대시보드 */
  dashboard: {
    title: "The Art of Logic",
    subtitle: ": BX Synergy Report",
    desc: "10년의 글로벌 미학과 비즈니스 로직을 연결하여\n기업의 실질적 가치를 설계합니다.",
    filterTabs: ["BX", "Visual Dir.", "Production", "Digital/Ai"],
    skills: [
      {
        name: "Visual Communication",
        pct: 90,
        sub: "Brand Identity Design : Logo, Typography, Brand Guideline",
        detail: "타겟 분석 기반의 브랜드 정체성 확립 및 시각화",
        cat: "BX",
      },
      {
        name: "Photography & Videography",
        pct: 100,
        sub: "Commercial Photo, Film Directing, Lighting",
        detail: "비주얼 톤앤매너 (사진 & 영상) 디렉팅",
        cat: "Visual Dir.",
      },
      {
        name: "Packaging Production Mgmt",
        pct: 100,
        sub: "CMYK Color Control, Post-press, Inspection",
        detail: "정교한 도수 관리 및 현장 인쇄 감리를 통한 구현력 최적화",
        cat: "Production",
      },
      {
        name: "AI & Digital Tools",
        pct: 78,
        sub: "Figma, Midjourney, Vibe Coding, Prompt Engineering",
        detail: "AI 바이브 코딩 레버리지 및 디지털 워크플로우 최적화",
        cat: "Digital/Ai",
      },
    ],
    chartBars: [
      { label: "BX", orange: 65, teal: 80 },
      { label: "Visual", orange: 90, teal: 100 },
      { label: "Pack.", orange: 45, teal: 60 },
      { label: "Prod.", orange: 80, teal: 100 },
      { label: "Digital", orange: 50, teal: 70 },
      { label: "Ai", orange: 70, teal: 78 },
    ],
  },

  /* ── 포트폴리오 (8개) */
  projects: [
    {
      id: 0,
      cat: "PACKAGING",
      genre: "Food",
      title: "Renewal",
      thumbnail: "/images/thumbnail_jerky.png",
      img: "/images/photo_jerky.png",
      bg: "#C8C4B8",
      isVideo: false,
      year: "2025",
      fullTitle: "머거본 육포 라인업 패밀리룩 리뉴얼",
      desc: "육포의 근본인 '본육포' 시리즈를 중심으로, 파편화되어 있던 기존 패키지들을 하나의 통합된 비주얼 시스템으로 재정립했습니다. 브랜드 헤리티지를 유지하면서도 현대적인 감각의 패밀리룩을 구현하여 브랜드 인지도를 강화했습니다.",
      tags: ["Package Design", "Renewal", "Visual Strategy", "Family-look"],
    },
    {
      id: 1,
      cat: "PACKAGING",
      genre: "Food",
      title: "Brand Identity",
      thumbnail: "/images/thumbnail_bellygom.png",
      img: "/images/belly_gom.png",
      bg: "#B8C4C0",
      isVideo: false,
      year: "2025",
      fullTitle: "벨리곰 x 호두정과 3종 콜라보 패키지",
      desc: "'벨리곰' 캐릭터의 친근함과 프리미엄 호두정과의 만남을 시각화한 프로젝트. 3가지 맛의 개성을 살리면서도 캐릭터를 눈에 띄게 배치하여, 혼잡한 오프라인 매대에서 시선 점유를 유도했습니다.",
      tags: ["Branding", "Identity", "Collaboration", "Character"],
    },
    {
      id: 2,
      cat: "BX",
      genre: "Character",
      title: "Packaging Design",
      thumbnail: "/images/thumbnail_seasoning_ms.png",
      img: "/images/seasoning_ms_ds.png",
      bg: "#C4B8C4",
      isVideo: false,
      year: "2024",
      fullTitle: "신규 브랜드 캐릭터 '시즈닝몬스터' 개발",
      desc: "기존 정형화된 캐릭터에서 탈피하여, 시즈닝의 맛에 따라 입술 색이 변하는 위트 있는 설정의 '시즈닝몬스터'를 개발했습니다. 캐릭터의 특징을 패키지 전면에 녹여내어 고객에게 감성적이고 즐거운 브랜드 경험(BX)을 제공합니다.",
      tags: ["Character", "BX", "Packaging", "Storytelling", "Monster"],
    },
    {
      id: 3,
      cat: "GRAPHIC DESIGN",
      genre: "Food",
      title: "Digital Design",
      thumbnail: "/images/thumbnail_bellygom_web_01.png",
      img: "/images/2026_Bellygom.jpeg",
      bg: "#C4C0B8",
      isVideo: false,
      year: "2026",
      fullTitle: "벨리곰 호두정과 이커머스 상세페이지",
      desc: "디지털 환경에서 벨리곰의 매력을 극대화하여 구매 전환율을 높이는 상세페이지를 설계했습니다. 직관적인 비주얼 그리드와 데이터 기반의 워크플로우를 통해 제품의 핵심 셀링 포인트를 효과적으로 전달하는 디지털 경험을 구현했습니다.",
      tags: ["Digital Design", "E-commerce", "UI/UX", "Visual Merchandising"],
    },
    {
      id: 4,
      cat: "VIDEOGRAPHY",
      genre: "Ads",
      title: "40th Campaign",
      thumbnail: "/images/thumbnail_40th.png",
      img: "/images/project5.png",
      video: "/videos/40th.mp4",
      bg: "#B8C0C8",
      isVideo: true,
      year: "2026",
      fullTitle: "머거본 40주년 기념 캠페인 (AI Full Production)",
      desc: "브랜드의 40년 역사와 미래 비전을 담은 광고 캠페인. 기획부터 스토리보드, 음악, 내레이션, 영상 생성까지 전 과정을 AI(Generative AI)로 제작했습니다. 최신 기술 레버리지를 통해 브랜드 헤리티지를 트렌디한 감각으로 재해석했습니다.",
      tags: ["AI Video", "Campaign", "Creative Directing", "Future Vision"],
    },
    {
      id: 5,
      cat: "VIDEOGRAPHY",
      genre: "Brand Film",
      title: "Music Video",
      thumbnail: "/images/thumbnail_nuts_for_u.png",
      img: "/images/project6.png",
      video: "/videos/Nuts_for_U.mp4",
      bg: "#C0C8BC",
      isVideo: true,
      year: "2026",
      fullTitle: "'너츠포유' 일상 밀착형 브랜드 필름",
      desc: "학교, 집, 직장 등 소비자의 실제 TPO(Time·Place·Occasion)에 맞춰 제작된 브랜드 필름. 평범한 일상의 순간마다 '너츠포유'가 함께한다는 메시지를 각기 다른 음악과 영상미로 표현하여 브랜드의 일상 점유율을 높이고자 했습니다.",
      tags: ["Brand Film", "TPO Strategy", "Directing", "Music Video"],
    },
    {
      id: 6,
      cat: "PHOTOGRAPHY",
      genre: "Commercial",
      title: "Product",
      thumbnail: "/images/thumbnail_ads_01.png",
      img: "/images/photo_ads_00.png",
      bg: "#C8C8C0",
      isVideo: false,
      year: "2019",
      fullTitle: "상업용 커머셜 및 프로덕트 포토그래피",
      desc: "제품 고유의 질감과 조형미를 극대화하기 위해 빛의 각도와 반사를 정밀하게 컨트롤했습니다. 매체별 특성에 최적화된 비주얼 톤을 도출하여 제품이 가진 프리미엄 가치를 시각적으로 증명한 프로젝트입니다.",
      tags: ["Commercial", "Lighting", "Product Photo", "Texture"],
    },
    {
      id: 7,
      cat: "PHOTOGRAPHY",
      genre: "Fashion",
      title: "Editorial",
      thumbnail: "/images/thumbnail_fashion_00.png",
      img: "/images/photo_fashion_00.png",
      bg: "#C4C0C8",
      isVideo: false,
      year: "2020",
      fullTitle: "패션 에디토리얼: 다양성의 미학",
      desc: "프랑스 유학 시절 진행한 에디토리얼 프로젝트. 다양한 스타일의 인물을 통해 개인의 고유한 아름다움과 독창성을 포착했습니다. 사회적 편견을 넘어, 각 개인이 자신을 자유롭게 표현할 수 있는 환경에 대한 지지를 시각적 서사로 기록했습니다.",
      tags: ["Editorial", "Fashion", "Art Direction", "Diversity", "Paris"],
    },
  ],

  /* ── 타임라인 (최신순) */
  timeline: [
    {
      id: 0,
      role: "BX 패키지 디자이너",
      type: "Professional",
      company: "머거본 | 세계식품(주)",
      loc: "대한민국",
      period: "2023 - 현재",
      dur: "2.7년",
      dot: true,
      detail:
        "머거본의 주력 제품(견과, 육포 등) 패키지 리뉴얼 및 BI 구축을 통해 브랜드 신뢰도를 강화하고 인지도를 상승시켰습니다. 단순히 패키지 제작에 그치지 않고, 온라인 상세페이지 리뉴얼, 홈페이지 리뉴얼을 병행하여 구매 전환율 상승과 매출 증대에 간접적으로 기여했습니다. 주니어 패키지 디자이너로서 인쇄 감리부터 현장 품질 관리까지 책임지며, 고객에게 일관되고 차별화된 브랜드 아이덴티티를 전달하고자 노력하고 있습니다.",
      tags: [
        "Brand Identity System",
        "Package Solution",
        "CMYK",
        "Post-press",
        "BX Strategy",
      ],
    },
    {
      id: 1,
      role: "포토그래퍼",
      type: "Freelance",
      company: "Fashion & Commercial Photography / Ex. Monoprix online",
      loc: "프랑스, 스페인, 대한민국",
      period: "2019 - 2023",
      dur: "5년",
      dot: false,
      detail:
        "프랑스 유통 대기업 Monoprix Online의 제품 사진 및 브랜드 캠페인을 담당하며 상업 비주얼의 정교함을 익혔습니다. 무드보드 기획부터 라이팅, 후반 보정까지 전 과정을 참여하며 '브랜드의 가치를 극대화하는 이미지'를 생산했습니다. 이때 확립한 높은 비주얼 감도는 현재 패키지와 디지털 매체를 아우르는 일관된 브랜드 경험(BX) 설계의 핵심 자산입니다.",
      tags: [
        "Fashion Photo",
        "Commercial",
        "Monoprix",
        "Europe",
        "Art Directing",
        "High-end Visual",
      ],
    },
    {
      id: 2,
      role: "그래픽 디자인 & 사진학",
      type: "Bachelor's degree",
      company: "ECOLE STUDIO CREA PARIS & SPEOS PARIS",
      loc: "프랑스 파리",
      period: "2016 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리 ECOLE STUDIO CREA(그래픽)와 SPEOS PARIS(사진)에서 복수 전공하며 디자인 이론과 시각 구현 능력을 체계적으로 훈련했습니다. 디자인 기획부터 최종 비주얼 제작까지 전 과정을 핸들링할 수 있는 '하이브리드 디자이너'로서의 역량을 갖추었으며, 졸업 작품전 참여를 통해 글로벌 수준의 크리에이티브 감각을 증명했습니다.",
      tags: [
        "Graphic Design",
        "Photography",
        "Paris School",
        "Grand Ecole",
        "Design Theory",
        "Fine Art",
      ],
    },
    {
      id: 3,
      role: "프랑스 유학",
      type: "Global Mind",
      company: "Fine Art & Fashion Marketing",
      loc: "프랑스 파리",
      period: "2012 - 2021",
      dur: "",
      dot: false,
      detail:
        "파리에서 약 10년간 파인아트와 패션 마케팅을 전공하며 유럽 크리에이티브 씬의 정점을 경험했습니다. 단순히 시각적 아름다움을 넘어, 브랜드가 소비자와 감성적으로 연결되는 '비주얼 스토리텔링'의 힘을 체득했습니다. 박물관과 갤러리에서 익힌 고전 미술의 비례감과 현대 디자인의 맥락은 현재 제가 전개하는 모든 BX 디자인의 독보적인 미적 근간이 되었습니다.",
      tags: [
        "European Aesthetics",
        "Visual Storytelling",
        "Global Experience",
        "Paris",
        "Fashion Marketing",
        "Fine Art",
      ],
    },
  ],

  /* ── 챗봇 Q&A */
  chatbot: {
    greeting: '"궁금하신 점이 있다면 무엇이든 물어보세요!"',
    questions: [
      {
        q: "패키지 디자이너에서 UI/UX로\n직무 영역을 확장하려는 이유는 무엇인가요?",
        a: "패키지 실무를 하면서 늘 아쉬웠던 점이, 고객이 우리 브랜드를 만나는 경험이 오프라인 제품 하나에서 끝난다는 것이었습니다. 요즘은 앱을 켜는 순간부터 브랜드 경험이 시작되잖아요. 익숙한 실물 디자인이라는 안전지대에 머물기보다, 디지털 환경까지 아우르는 디자이너로 빠르게 성장하고 싶어 지원했습니다.",
      },
      {
        q: "프랑스 10년 유학 경험과 패션 사진 경력이\n뷰티 플랫폼에 어떤 강점이 될 수 있나요?",
        a: "요즘은 AI를 적극적으로 활용하면 어떤 디자인 툴이든 빠르게 마스터할 수 있다고 생각합니다. 실제로 지금 보시는 이 웹앱 포트폴리오 역시 직접 기획하고 AI 바이브 코딩을 레버리지해 구현해 낸 결과물입니다. 저의 강점은 툴 숙련도 자체보다는 다년간 현장에서 길러낸 '비주얼 감도'에 있습니다.",
      },
      {
        q: "기획이나 마케팅 등 타 부서와 협업할 때\n가장 중요하게 생각하는 원칙은 무엇인가요?",
        a: "저는 직무의 경계를 허물고 '원팀(One Team)'으로 움직이는 것을 가장 중요하게 생각합니다. 디자인은 마케팅과 기획의 의도를 고객의 마음에 꽂히게 만드는 가장 직관적인 언어입니다. 공동의 비즈니스 목표를 향해 동료들과 유기적으로 피드백을 주고받으며 최적의 시각적 솔루션을 함께 발전시켜 나가겠습니다.",
      },
    ],
  },
};
